### ISSUE TITLE
Overwrite drush path or add pre-command hook

### ISSUE THREAD

**Issue by MuschPusch** [factorial-io/fabalicious#41]
On some restrictive environments it's impossible to get drush running since no .profile, .bash_profile is loaded and drush executions ends in a command not found. 

Possible fixes: 
- pre command hook to set a variable like PATH or execute an alias 
- overwrite the path to drush

**Comment by MuschPusch** [comment]
Workaround: 

```deployFinished:
 - path/to/drush en rmh_deploy -y
 - path/to/drush updb -y
 - path/to/drush fra -y
 - path/to/drush cc all
```
and overwrite the needs for that 'special' server
```needs:
     - ssh
     - git
     - files```

**Comment by stmh** [comment]
This is a nice feature request!

Using PATHs might not work on environments which do not support full-fledged shells (e.g. omega8cc) Fabric depends on bash on the remote host to support environment-variables. Nevertheless it might be a good idea to add support for custom environment variables. 

To support custom executable paths I'd propose the following solution: Similar to the expansion of host-settings in scripts (`%host.bla%`) I'd introduce a special notation for executables, which can be overridden by the fabfile.yaml:

```yaml
host:
  a.host:
    executables:
      my_app: /opt/local/my_app
      drush: /bin/echo
   script:
      example:
        - "cd %host.gitRootFolder%; #!my_app --toTheWork ."
        - "cd %host.siteFolder%; #!drush cc all"
```

Please have a look at the implementation in the feature-branch `feature/configurable-executables` -- it needs more testing but looks promising
